// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using EDG_B2B.Data;

#nullable disable

namespace EDG_B2B.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724203654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EDG_B2B.Entity.Bayi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SatisBayiiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.HasIndex("SatisBayiiId");

                    b.HasIndex("VergiNo")
                        .IsUnique();

                    b.ToTable("Bayiler");
                });

            modelBuilder.Entity("EDG_B2B.Entity.BayiUrunFiyat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GecerlilikBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GecerlilikBitis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OzelFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("BayiId", "UrunId")
                        .IsUnique();

                    b.ToTable("BayiUrunFiyatlari");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("KdvTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SiparisId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FaturaNo")
                        .IsUnique();

                    b.HasIndex("SiparisId")
                        .IsUnique();

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailDogrulamaTokeni")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailDogrulandiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EmailDogrulanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OnayNotu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("OnaylanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OnaylayanAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmailDogrulamaTokeni");

                    b.HasIndex("OnaylayanAdminId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EDG_B2B.Entity.KullaniciOturumu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("KullaniciId", "IsRevoked");

                    b.ToTable("KullaniciOturumlari");
                });

            modelBuilder.Entity("EDG_B2B.Entity.SatisBayii", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("SatisBayiler");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Sepet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.ToTable("Sepetler");
                });

            modelBuilder.Entity("EDG_B2B.Entity.SepetUrun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("SepetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SepetId");

                    b.HasIndex("UrunId");

                    b.ToTable("SepetUrunleri");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Siparis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<Guid>("OnaylayanSatisBayiiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SepetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanSatisBayiiId");

                    b.HasIndex("SepetId")
                        .IsUnique();

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("EDG_B2B.Entity.SiparisUrun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("SatirToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SiparisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisUrunleri");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Urun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("KdvOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("StandartFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StokKodu")
                        .IsUnique();

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Bayi", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Kullanici", "Kullanici")
                        .WithOne("Bayi")
                        .HasForeignKey("EDG_B2B.Entity.Bayi", "KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EDG_B2B.Entity.SatisBayii", "SatisBayii")
                        .WithMany("Bayiler")
                        .HasForeignKey("SatisBayiiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");

                    b.Navigation("SatisBayii");
                });

            modelBuilder.Entity("EDG_B2B.Entity.BayiUrunFiyat", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Bayi", "Bayi")
                        .WithMany("BayiUrunFiyatlari")
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EDG_B2B.Entity.Urun", "Urun")
                        .WithMany("BayiUrunFiyatlari")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Fatura", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Siparis", "Siparis")
                        .WithOne("Fatura")
                        .HasForeignKey("EDG_B2B.Entity.Fatura", "SiparisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Kullanici", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Kullanici", "OnaylayanAdmin")
                        .WithMany()
                        .HasForeignKey("OnaylayanAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OnaylayanAdmin");
                });

            modelBuilder.Entity("EDG_B2B.Entity.KullaniciOturumu", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EDG_B2B.Entity.SatisBayii", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Kullanici", "Kullanici")
                        .WithOne("SatisBayii")
                        .HasForeignKey("EDG_B2B.Entity.SatisBayii", "KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Sepet", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Bayi", "Bayi")
                        .WithMany("Sepetler")
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bayi");
                });

            modelBuilder.Entity("EDG_B2B.Entity.SepetUrun", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Sepet", "Sepet")
                        .WithMany("SepetUrunleri")
                        .HasForeignKey("SepetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EDG_B2B.Entity.Urun", "Urun")
                        .WithMany("SepetUrunleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sepet");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Siparis", b =>
                {
                    b.HasOne("EDG_B2B.Entity.SatisBayii", "OnaylayanSatisBayii")
                        .WithMany()
                        .HasForeignKey("OnaylayanSatisBayiiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EDG_B2B.Entity.Sepet", "Sepet")
                        .WithOne("Siparis")
                        .HasForeignKey("EDG_B2B.Entity.Siparis", "SepetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OnaylayanSatisBayii");

                    b.Navigation("Sepet");
                });

            modelBuilder.Entity("EDG_B2B.Entity.SiparisUrun", b =>
                {
                    b.HasOne("EDG_B2B.Entity.Siparis", "Siparis")
                        .WithMany("SiparisUrunleri")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EDG_B2B.Entity.Urun", "Urun")
                        .WithMany("SiparisUrunleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Bayi", b =>
                {
                    b.Navigation("BayiUrunFiyatlari");

                    b.Navigation("Sepetler");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Kullanici", b =>
                {
                    b.Navigation("Bayi");

                    b.Navigation("SatisBayii");
                });

            modelBuilder.Entity("EDG_B2B.Entity.SatisBayii", b =>
                {
                    b.Navigation("Bayiler");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Sepet", b =>
                {
                    b.Navigation("SepetUrunleri");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Siparis", b =>
                {
                    b.Navigation("Fatura");

                    b.Navigation("SiparisUrunleri");
                });

            modelBuilder.Entity("EDG_B2B.Entity.Urun", b =>
                {
                    b.Navigation("BayiUrunFiyatlari");

                    b.Navigation("SepetUrunleri");

                    b.Navigation("SiparisUrunleri");
                });
#pragma warning restore 612, 618
        }
    }
}
